name: DXF to PNG Converter
on:
  push:
    branches:
      - main
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Convert DXF to PNG
        run: |
          mkdir -p output
          for file in dxf_files/*.dxf; do
            docker run --rm \
              -v ${{ github.workspace }}:/workdir \
              zbyue/dxf2png \
              "/workdir/$file" \
              "/workdir/output/$(basename "${file%.*}").png"
          done
      - name: Move PNG files to output directory
        run: |
          mkdir -p output
          mv *.png output/
