name: Convert DXF to PNG
on:
  push:
    paths:
      - 'all_dxf/*.dxf'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install DXF converter
        run: docker build --rm -t dxf2png .
      - name: Convert DXF to PNG
        run: |
          for file in $(find . -name 'all_data/*.dxf'); do
            docker run --rm -v "$(pwd)":/data pavlobu/dxf2png /data/$file /data/${file%.*}.png
          done
      - name: Move PNG files to folder
        run: |
          mkdir -p png
          mv /data/*.png all_preview/
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Convert DXF files to PNG"
