name: DXF to PNG Converter
on:
  push:
    branches:
      - main
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Convert DXF to PNG
        run: |
          mkdir -p output
          for file in all_dxf/*.dxf; do
            docker run --rm \
              -v ${{ github.workspace }}/all_dxf:/workdir:ro \
              -v ${{ github.workspace }}/output:/output \
              miq42/dxf2png \
              "/workdir/$file" \
              "/output/$(basename "${file%.*}").png"
          done
