name: Convert DXF to PNG

on: push

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install libcairo2-dev libpng-dev git
    - name: Clone dxf2png repository
      run: git clone https://github.com/iamjinlei/dxf2png.git
    - name: Build dxf2png
      run: |
        cd dxf2png
        docker build --rm -t dxf2png .
    - name: Convert DXF to PNG
      run: |
        mkdir -p all_preview
        for f in all_dxf/*.dxf; do
          filename=$(basename -- "$f")
          extension="${filename##*.}"
          filename="${filename%.*}"
          ./convert.sh "$f" "all_preview/${filename}.png"
        done
