name: Convert DXF files to PNG

on:
  push:
    branches:
      - main

jobs:
  convert_dxf_to_png:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install matplotlib ezdxf

    - name: Convert DXF files to PNG
      run: |
        python dxf2img.py

    - name: Move PNG files to all_preview folder
      run: |
        mkdir all_preview
        mv *.png all_preview/
