name: Convert DXF to PNG

on:
  push:
    paths:
      - all_dxf/**
  
jobs:
  dxf2png:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dxf2png
  
      - name: Convert DXF to PNG
        run: |
          mkdir -p all_preview
          for file in all_dxf/*.dxf; do
            filename=$(basename -- "$file")
            filename="${filename%.*}"
            dxf2png "$file" "all_preview/${filename}.png"
          done
  