name: Convert DXF to PNG and commit to repo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  convert_dxf_to_png:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ezdxf matplotlib

    - name: Convert DXF files to PNG
      run: python convert_dxf_to_png.py all_dxf --img-format png --img-res 96

    - name: Check if there are changes to commit
      run: |
        if [[ -n $(git status -s all_preview/) ]]; then
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add all_preview/
          git commit -m "Convert DXF files to PNG"
          git push
        else
          echo "No changes to commit"
        fi
