name: Convert DXF to PNG
on:
  push:
    branches:
      - main
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update && \
        sudo apt-get install -y libjpeg-dev libfreetype6-dev zlib1g-dev && \
        pip install --user ezdxf pillow
    - name: Convert DXF to PNG
      run: |
        mkdir all_preview
        for file in all_dxf/*.dxf
        do
          filename=$(basename -- "$file")
          filename="${filename%.*}"
          if [ ! -f "all_preview/${filename}.png" ]; then
            python3 -c "import ezdxf, sys; sys.stdout.buffer.write(ezdxf.zoom.extents_layout(sys.argv[1]).png())" "$file" > "all_preview/${filename}.png"
          fi
        done
