name: Convert DXF to PNG
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt
    - name: Install dxf2image crate
      run: cargo install dxf2image
    - name: Convert DXF to PNG
      run: |
        for f in all_dxf/*.dxf; do
          filename=$(basename "$f" .dxf)
          if [ ! -f "all_preview/${filename}.png" ]; then
            dxf2image -i "$f" -o "all_preview/${filename}.png"
          else
            echo "File all_preview/${filename}.png already exists, skipping."
          fi
        done
