name: DXF to PNG Converter
on:
  push:
    branches:
      - main
jobs:
  convert:
    runs-on: ubuntu-latest
    env:
      QT_QPA_PLATFORM: offscreen
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install librecad
        run: |
          sudo apt-get update
          sudo apt-get install -y librecad
      - name: Convert DXF to PNG
        run: |
          mkdir -p all_preview
          for file in all_dxf/*.dxf; do
            filename=$(basename -- "$file")
            extension="${filename##*.}"
            filename="${filename%.*}"
            if [ -f "all_preview/${filename}.png" ]; then
              echo "Skipping ${filename}.png"
            else
              echo "Converting ${filename}.dxf to ${filename}.png"
              librecad -x 0 -y 0 -z 1 -p 1 -b 1 "$file" "all_preview/${filename}.png"
            fi
          done
      - name: Move PNG files to all_preview folder
        run: |
          mkdir -p all_preview
          mv *.png all_preview/
