name: Convert DXF to PNG
on:
  push

jobs:
  convert-dxf-to-png:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Check out the repository
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Use the latest version of Python 3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ezdxf pillow
    - name: Convert DXF to PNG
      run: |
        python dxf_to_png.py all_dxf all_preview # Run the Python script, passing in the input and output directories
      env:
        INPUT_DIR: all_dxf
        OUTPUT_DIR: all_preview
    - name: Move PNG files
      run: |
        mkdir -p "${{ env.OUTPUT_DIR }}" # Create the output directory if it doesn't exist
        find "${{ env.INPUT_DIR }}" -name '*.dxf' | while read dxf_file; do
          png_file="${{ env.OUTPUT_DIR }}/${dxf_file##*/}.png" # Construct the PNG file name based on the DXF file name
          if [ ! -f "$png_file" ]; then # Skip the file if the PNG file already exists
            python dxf_to_png.py "$dxf_file" "$png_file"
          fi
        done
