name: Convert DXF to PNG

on:
  push

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Convert DXF to PNG
        run: python convert_dxf_to_png.py

      - name: Move PNG files to all_preview folder
        run: |
          mkdir all_preview
          mv *.png all_preview/
