name: Convert DXF to PNG
on:
  push:
    branches: [main]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install dxfgrabber Pillow
    - name: Convert DXF to PNG
      run: |
        python3 dxf2png.py